

CREATE TABLE Station_Dimension(
Station_ID			number,
Station_name		varchar2(70),
Station_latitude	number,
Station_longitude	number,
Zipcode				varchar2(12),
Neighborhood		varchar2(50),
Borough				varchar2(50),
primary key(Station_ID)
);


CREATE TABLE User_Dimension(
User_ID				number GENERATED BY DEFAULT ON NULL AS IDENTITY,
Usertype			varchar2(10),
Birth_Year			number,
Age					number,
Gender				number,
GenderName			varchar2(10),
primary key(User_ID)
);

CREATE TABLE Date_Dimension(
Date_ID				number,
Ride_Day			number,
Ride_Week			number,
Ride_Month			number,
Ride_Year			number,
Weekdays			varchar2(10),
primary key(Date_ID)
);

CREATE TABLE Route_Dimension(
RoutePath_ID		number GENERATED BY DEFAULT ON NULL AS IDENTITY,
Route_Path_Bor		varchar2(150),
primary key (RoutePath_ID)
);

CREATE TABLE BikeUsage_Fact (
BikeUsage_ID		number GENERATED BY DEFAULT ON NULL AS IDENTITY,
Bike_ID				number,
RoutePath_ID		number,
Station_ID_S		number,
Station_ID_E		number,
Date_ID				number,
Duration			number,
primary key (BikeUsage_ID),
foreign key(RoutePath_ID) references Route_Dimension(RoutePath_ID),
foreign key(Station_ID_S) references Station_Dimension(Station_ID),
foreign key(Station_ID_E) references Station_Dimension(Station_ID),
foreign key(Date_ID) references Date_Dimension(Date_ID)
);

CREATE TABLE Ridership_Fact(
Ridership_ID		number GENERATED BY DEFAULT ON NULL AS IDENTITY,
User_ID				number,
Station_ID_S		number,
Station_ID_E		number,
Date_ID				number,
Duration			number,
primary key(Ridership_ID),
foreign key(User_ID) references User_Dimension(User_ID),
foreign key(Station_ID_S) references Station_Dimension(Station_ID),
foreign key(Station_ID_E) references Station_Dimension(Station_ID),
foreign key(Date_ID) references Date_Dimension(Date_ID)
);

CREATE TABLE data_processed (
filename		varchar2(50),
bad_records		number,
primary key (filename));


INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Brooklyn to Brooklyn');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Brooklyn to Manhattan');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Brooklyn to Queens');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Brooklyn to The Bronx');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Brooklyn to Staten Island');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Manhattan to Brooklyn');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Manhattan to Manhattan');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Manhattan to Queens');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Manhattan to The Bronx');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Manhattan to Staten Island');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Queens to Brooklyn');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Queens to Manhattan');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Queens to Queens');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Queens to The Bronx');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Queens to Staten Island');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('The Bronx to Brooklyn');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('The Bronx to Manhattan');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('The Bronx to Queens');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('The Bronx to The Bronx');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('The Bronx to Staten Island');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Staten Island to Brooklyn');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Staten Island to Manhattan');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Staten Island to Queens');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Staten Island to The Bronx');
INSERT INTO Route_Dimension (Route_Path_Bor) VALUES ('Staten Island to Staten Island');